name: rei
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: https://github.com/rei-ui/rei
description: Polymer components for ten foot user interfaces
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: '1.0.0-rc.6'
  reflectable: '^0.3.3'
  web_components: '^0.12.0+3'
dev_dependencies:
  test: '^0.12.5+1'
  dart_to_js_script_rewriter: '^0.1.0+4'
transformers:
- web_components
- reflectable
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
- dart_to_js_script_rewriter
