name: rei
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: https://github.com/rei-ui/rei
description: Polymer components for ten foot user interfaces
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.2+2
  less_dart: ^0.3.3
dev_dependencies:
  test: ^0.12.5+1
transformers:
- less_dart:
    compress: true
- polymer:
    entry_points:
    - test/src/animation/computed_timing_test.html
    - test/src/selection/linear_selectable_test.html
    - web/animation/index.html
    - web/scrolling/index.html
    - web/selection/index.html
    - web/transform/index.html
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
