name: rei
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: https://github.com/rei-ui/rei
description: Polymer components for ten foot user interfaces
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: '1.0.0-rc.9'
  reflectable: '^0.4.0'
  web_components: '^0.12.0+3'
  less_dart: '^0.3.2'
dev_dependencies:
  test: '^0.12.5+1'
transformers:
- web_components:
    entry_points:
    - test/src/selection/linear_selectable_test.html
    - web/scrolling/index.html
    - web/selection/index.html
    - web/transform/index.html
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- reflectable:
    entry_points:
    - test/src/selection/linear_selectable_test.dart
    - web/scrolling/main.dart
    - web/selection/main.dart
    - web/transform/main.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
